# Generated by Django 6.0.1 on 2026-02-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0003_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
    ]
