# Generated by Django 6.0.1 on 2026-02-17 12:57

import app_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0006_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_video',
            field=models.FileField(upload_to=app_video.models.video_directory_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=app_video.models.video_directory_path),
        ),
    ]
